### PR TITLE
Set node-role.kubernetes.io based on MicroShift roles

### LINKED ISSUE #661: [BUG] Microshift does not honor /etc/microshift/config.yaml `roles` array
#### What happened: 
Microshift does not apply the `roles` listed in the config file defined at `/etc/microshift/config.yaml` despite documented behavior [here](https://microshift.io/docs/user-documentation/configuring/#configuration).

**Example:**
```
[core@pi-master-0 ~]$ cat /etc/microshift/config.yaml 
---
dataDir: /var/lib/microshift
roles:
  - controlplane
  - node
nodeName: "pi-master-0"
cluster:
  clusterCIDR: "10.42.0.0/16"
  serviceCIDR: "10.43.0.0/16"
  dns: "10.43.0.10"
  domain: cluster.local
```

**Result:**
```
[core@pi-master-0 ~]$ oc get nodes
NAME          STATUS   ROLES    AGE   VERSION
pi-master-0   Ready    <none>   22h   v1.21.0
```

#### What you expected to happen: 
That the `ROLES` column of `oc get nodes` would reflect `controlplane,node`:
```
[core@pi-master-0 ~]$ oc get nodes
NAME          STATUS   ROLES                  AGE   VERSION
pi-master-0   Ready     controlplane,node  22h     v1.21.0
```

#### How to reproduce it (as minimally and precisely as possible):

1. Define `/etc/microshift/config.yaml` with `roles` array inclusive of the two documented acceptable roles `controleplane` and `node`
2. Pull the [documented](https://microshift.io/docs/getting-started/#deploying-microshift) for podman `microshift.service` systemd unit, enable it, and start it:
```
$ sudo curl -o /etc/systemd/system/microshift.service \
     https://raw.githubusercontent.com/redhat-et/microshift/main/packaging/systemd/microshift-containerized.service
$ sudo systemctl enable microshift.service
$ sudo systemctl start microshift.service
```
3. Execute `oc get nodes` and note the `ROLES` column of the output

#### Environment:
- Microshift version (use `microshift version`): latest
- Hardware configuration: Raspberry Pi 400 (aarch64, 4GB RAM)
- OS (e.g: `cat /etc/os-release`): Fedora CoreOS 35.20220327.3.0
- Kernel (e.g. `uname -a`): Linux pi-master-0 5.16.16-200.fc35.aarch64 #1 SMP Sat Mar 19 13:35:51 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
- Others: microshift.service in more readable form:
```
[core@pi-master-0 ~]$ cat /etc/systemd/system/microshift.service 
[Unit]
Description=MicroShift Containerized
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target crio.service
After=network-online.target crio.service
RequiresMountsFor=%t/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStartPre=/usr/bin/mkdir -p /var/lib/kubelet ; /usr/bin/mkdir -p /var/hpvolumes
ExecStartPre=/bin/rm -f %t/%n.ctr-id
ExecStart=/bin/podman run \
  --cidfile=%t/%n.ctr-id \
  --cgroups=no-conmon \
  --rm \
  --replace \
  --sdnotify=container \
  --label io.containers.autoupdate=registry \
  --network=host \
  --privileged \
  -d \
  --name microshift \
  -v /var/hpvolumes:/var/hpvolumes:z,rw,rshared \
  -v /var/run/crio/crio.sock:/var/run/crio/crio.sock:rw,rshared \
  -v microshift-data:/var/lib/microshift:rw,rshared \
  -v /var/lib/kubelet:/var/lib/kubelet:z,rw,rshared \
  -v /var/log:/var/log \
  -v /etc:/etc quay.io/microshift/microshift:latest
ExecStop=/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all

[Install]
WantedBy=multi-user.target default.target
```

### PR DESCRIPTION
**Pull request by pmtk**
**Which issue(s) this PR addresses**:
Closes #661  [USHIFT-28](https://issues.redhat.com/browse/USHIFT-28)

**Desc**
Adds node labeling based on MicroShift roles. There's a slight difference between MicroShift's and kubelet's roles: [control-plane vs controlplane, worker vs node](https://github.com/openshift/microshift/blob/79b64b05d843d2a4aa2c7a406276ece69d019f81/vendor/k8s.io/kubelet/pkg/apis/well_known_labels.go#L50)

### CODE REVIEW

File: pkg/node/kubelet.go [hunk 1]
```diff
@@ -70,6 +70,14 @@ func (s *KubeletServer) configure(cfg *config.MicroshiftConfig) {
 	kubeletFlags.NodeIP = cfg.NodeIP
 	kubeletFlags.ContainerRuntime = "remote"
 	kubeletFlags.RemoteRuntimeEndpoint = "unix:///var/run/crio/crio.sock"
+	for _, role := range cfg.Roles {
+		if role == "controlplane" {
+			kubeletFlags.NodeLabels["node-role.kubernetes.io/control-plane"] = ""
```
Comment (pmtk) [inline pkg/node/kubelet.go:75]: Question: should we include `"node-role.kubernetes.io/master"` as well?

**Comment by oglok** [comment]
```
[root@maxwell ~]# oc --kubeconfig=kubeconfig-clusterbot get node
NAME                                       STATUS   ROLES                  AGE   VERSION
ci-ln-cw0ryxb-72292-nqblm-master-0         Ready    control-plane,master   30m   v1.24.0+da80cd0
ci-ln-cw0ryxb-72292-nqblm-master-1         Ready    control-plane,master   30m   v1.24.0+da80cd0
ci-ln-cw0ryxb-72292-nqblm-master-2         Ready    control-plane,master   30m   v1.24.0+da80cd0
ci-ln-cw0ryxb-72292-nqblm-worker-a-r5bqn   Ready    worker                 21m   v1.24.0+da80cd0
ci-ln-cw0ryxb-72292-nqblm-worker-b-868mp   Ready    worker                 21m   v1.24.0+da80cd0
ci-ln-cw0ryxb-72292-nqblm-worker-c-jcpbf   Ready    worker                 21m   v1.24.0+da80cd0
```

Let's go for the same labels that are present in OpenShift. @dhellmann

**Comment by dhellmann** [comment]
Yes, let's be consistent with standalone OpenShift.

**Comment by pmtk** [comment]
Added `master`

**Comment by ggiguash** [comment]
Closes USHIFT-28
